server {
    listen 80;
    server_name tomaszkostur.xyz www.tomaszkostur.xyz;

    # App 1 at /
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # App 2 at /react_demo/
    location /react_demo/ {
        alias /var/www/html/react_demo/;
        index index.html;
        try_files $uri $uri/ /react_demo/index.html;
    }
}