server {
  listen 8080;
  server_name _;

  # root /usr/share/nginx/html;
  root /var/www/html;
  index index.html;

  # root landing page
  location / {
    try_files $uri $uri/ /index.html;
  }

    # App 2 at /react_demo/
    # copy dist files into /var/www/react_demo/
    location /react_demo/ {
        alias /var/www/html/react_demo/;
        index index.html;
        try_files $uri $uri/ /react_demo/index.html;
    }  
}